DSW1.Proyecto_Tienda_Zapatillas.Web/Models/Colaborador/MergeColaborador.cs
using DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador.Select;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador
{
    public class MergeColaborador
    {
        [Required(ErrorMessage = "El DNI es obligatorio.")]
        [RegularExpression(@"^\d{8}$", ErrorMessage = "El DNI debe tener 8 dígitos.")]
        public string DNI { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(50, ErrorMessage = "El nombre no puede tener más de 50 caracteres.")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El apellido paterno es obligatorio.")]
        [StringLength(50, ErrorMessage = "El apellido paterno no puede tener más de 50 caracteres.")]
        public string ApePaterno { get; set; }

        [Required(ErrorMessage = "El apellido materno es obligatorio.")]
        [StringLength(50, ErrorMessage = "El apellido materno no puede tener más de 50 caracteres.")]
        public string ApeMaterno { get; set; }

        [Required(ErrorMessage = "El sexo es obligatorio.")]
        [StringLength(10, ErrorMessage = "El sexo no puede tener más de 10 caracteres.")]
        public string Sexo { get; set; }

        [Required(ErrorMessage = "El sueldo es obligatorio.")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "El sueldo debe tener un formato decimal válido.")]
        public double Sueldo { get; set; }

        [Required(ErrorMessage = "El teléfono es obligatorio.")]
        [StringLength(15, ErrorMessage = "El teléfono no puede tener más de 15 caracteres.")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "La dirección es obligatoria.")]
        [StringLength(100, ErrorMessage = "La dirección no puede tener más de 100 caracteres.")]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "Seleccione un Cargo")]
        public string IdCargo { get; set; }

        [Required(ErrorMessage = "Seleccione un estado")]
        public string IdEstado { get; set; }

        [Required(ErrorMessage = "Seleccione un distrito")]
        public string IdDistrito { get; set; }

        [BindNever]
        public string Mensaje { get; set; } = string.Empty;


        // Extra

        [Required(ErrorMessage = "Selecciona una provincia")]
        public int IdProvincia { get; set; }

        [Required(ErrorMessage = "Selecciona una provincia")]
        public List<Provincia> Provincias { get; set; }

        [Required(ErrorMessage = "Selecciona una provincia")]
        public List<Cargo> Cargos { get; set; }

        [Required(ErrorMessage = "Selecciona una provincia")]
        public List<Estado> Estados { get; set; }
    }

}

DSW1.Proyecto_Tienda_Zapatillas.Web/Models/Colaborador/Select/Cargo.cs
namespace DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador.Select
{
    public class Cargo
    {
        public int IdCargo { get; set; }
        public string Descripcion { get; set; } = string.Empty;
    }
}

DSW1.Proyecto_Tienda_Zapatillas.Web/Models/Colaborador/Select/Distrito.cs
namespace DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador.Select
{
    public class Distrito
    {
        public int IdProvincia { get; set; }
        public int IdDistrito { get; set;}
        public string Descripcion { get; set; } = string.Empty;
    }
}

DSW1.Proyecto_Tienda_Zapatillas.Web/Models/Colaborador/Select/Estado.cs
namespace DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador.Select
{
    public class Estado
    {
        public int IdEstado { get; set; }
        public string Descripcion { get; set; } = string.Empty;
    }
}

DSW1.Proyecto_Tienda_Zapatillas.Web/Models/Colaborador/Select/Provincia.cs
namespace DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador.Select
{
    public class Provincia
    {
        public int IdProvincia { get; set; }
        public string Descripcion { get; set; } = string.Empty;
    }
}

DSW1.Proyecto_Tienda_Zapatillas.Web/Controllers/ColaboradorController.cs
using DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Acceso;
using DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador;
using DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador.Select;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Newtonsoft.Json;
using System.Data;

namespace DSW1.Proyecto_Tienda_Zapatillas.Web.Controllers
{
    [Authorize]
    public class ColaboradorController : Controller
    {
        public readonly IConfiguration? _configuration;

        public ColaboradorController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        private List<Provincia> ObtenerProvincias()
        {
            List<Provincia> provincias = new List<Provincia>();

            try
            {
                using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("cnDB")))
                {
                    using (SqlCommand command = new SqlCommand("SELECT IdProvincia, Descripcion FROM Provincia", connection))
                    {
                        connection.Open();

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                Provincia provincia = new Provincia();
                                provincia.IdProvincia = Convert.ToInt32(reader["IdProvincia"]);
                                provincia.Descripcion = reader["Descripcion"].ToString();
                                provincias.Add(provincia);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error en busqueda de provincias";
            }

            return provincias;
        }

        private List<Cargo> ObtenerCargo()
        {
            List<Cargo> cargos = new List<Cargo>();

            try
            {
                using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("cnDB")))
                {
                    using (SqlCommand command = new SqlCommand("SELECT IdCargo, Descripcion FROM Cargo;", connection))
                    {
                        connection.Open();

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                Cargo cargo = new Cargo();
                                cargo.IdCargo = Convert.ToInt32(reader["IdCargo"]);
                                cargo.Descripcion = reader["Descripcion"].ToString();
                                cargos.Add(cargo);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error en busqueda de cargos";
            }

            return cargos;
        }

        private List<Estado> ObtenerEstado()
        {
            List<Estado> estados = new List<Estado>();

            try
            {
                using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("cnDB")))
                {
                    using (SqlCommand command = new SqlCommand("SELECT IdEstado, Descripcion FROM Estado;", connection))
                    {
                        connection.Open();

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                Estado estado = new Estado();
                                estado.IdEstado = Convert.ToInt32(reader["IdEstado"]);
                                estado.Descripcion = reader["Descripcion"].ToString();
                                estados.Add(estado);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Error en busqueda de Estados";
            }

            return estados;
        }


        public IActionResult GetDistritosByProvincia(int idProvincia)
        {
            List<Distrito> distritos = new List<Distrito>();

            using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("cnDB")))
            {
                using (SqlCommand command = new SqlCommand("GetDistritosByProvincia", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@IdProvincia", idProvincia);

                    connection.Open();

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Distrito distrito = new Distrito();
                            distrito.IdDistrito = Convert.ToInt32(reader["IdDistrito"]);
                            distrito.Descripcion = reader["Descripcion"].ToString();
                            distritos.Add(distrito);
                        }
                    }
                }
            }

            return Json(distritos);
        }



        public IActionResult MergeColaborador()
        {
            var colaborador = new MergeColaborador();
            colaborador.Provincias = ObtenerProvincias(); // Inicializa la propiedad Provincias con una lista de provincias
            colaborador.Cargos = ObtenerCargo();
            colaborador.Estados = ObtenerEstado();


            return View(colaborador);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MergeColaborador(MergeColaborador colaborador)
        {
            string mensaje = string.Empty;

            try
            {
                using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("cnDB")))
                {
                    using (SqlCommand command = new SqlCommand("sp_mergeColaborador", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;

                        command.Parameters.AddWithValue("@DNI", colaborador.DNI);
                        command.Parameters.AddWithValue("@Nombre", colaborador.Nombre);
                        command.Parameters.AddWithValue("@ApePaterno", colaborador.ApePaterno);
                        command.Parameters.AddWithValue("@ApeMaterno", colaborador.ApeMaterno);
                        command.Parameters.AddWithValue("@Sexo", colaborador.Sexo);
                        command.Parameters.AddWithValue("@Sueldo", colaborador.Sueldo);
                        command.Parameters.AddWithValue("@Telefono", colaborador.Telefono);
                        command.Parameters.AddWithValue("@Direccion", colaborador.Direccion);
                        command.Parameters.AddWithValue("@IdCargo", colaborador.IdCargo);
                        command.Parameters.AddWithValue("@IdEstado", colaborador.IdEstado);
                        command.Parameters.AddWithValue("@IdDistrito", colaborador.IdDistrito);

                        SqlParameter mensajeParam = new SqlParameter("@Mensaje", SqlDbType.VarChar, 100);
                        mensajeParam.Direction = ParameterDirection.Output;
                        command.Parameters.Add(mensajeParam);

                        connection.Open();
                        command.ExecuteNonQuery();

                        mensaje = mensajeParam.Value.ToString();
                    }
                }
            }
            catch (Exception ex)
            {
                mensaje = "Error en la ejecución del procedimiento almacenado: " + ex.Message;
            }

            ViewBag.Mensaje = mensaje;
            colaborador.Provincias = ObtenerProvincias();
            colaborador.Cargos = ObtenerCargo();
            colaborador.Estados = ObtenerEstado();
            ModelState.Clear();

            return View(colaborador);
        }



    }
}

DSW1.Proyecto_Tienda_Zapatillas.Web/Views/Colaborador/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

DSW1.Proyecto_Tienda_Zapatillas.Web/Views/Colaborador/MergeColaborador.cshtml
@model DSW1.Proyecto_Tienda_Zapatillas.Web.Models.Colaborador.MergeColaborador

@{
    ViewData["Title"] = "MergeColaborador";
}


<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<h1>MergeColaborador</h1>




<h4>MergeColaborador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="MergeColaborador">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApePaterno" class="control-label"></label>
                <input asp-for="ApePaterno" class="form-control" />
                <span asp-validation-for="ApePaterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApeMaterno" class="control-label"></label>
                <input asp-for="ApeMaterno" class="form-control" />
                <span asp-validation-for="ApeMaterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <select asp-for="Sexo" class="form-control">
                    <option value="Masculino">Masculino</option>
                    <option value="Femenino">Femenino</option>
                </select>
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Sueldo" class="control-label"></label>
                <input asp-for="Sueldo" class="form-control" />
                <span asp-validation-for="Sueldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="cargo">Cargo:</label>
                <select class="form-control" id="cargo" name="IdCargo">
                    <option value="">Seleccione un cargo</option>
                    @foreach (var cargo in Model.Cargos)
                    {
                        <option value="@cargo.IdCargo">@cargo.Descripcion</option>
                    }
                </select>
            </div>


            <div class="form-group">
                <label for="estado">Estado:</label>
                <select class="form-control" id="estado" name="IdEstado">
                    <option value="">Seleccione un estado</option>
                    @foreach (var estado in Model.Estados)
                    {
                        <option value="@estado.IdEstado">@estado.Descripcion</option>
                    }
                </select>
            </div>


            <div class="form-group">
                <label for="provincia">Provincia:</label>
                <select class="form-control" id="provincia" name="provincia">
                    <option value="">Seleccione una provincia</option>
                    @foreach (var provincia in Model.Provincias)
                    {
                        <option value="@provincia.IdProvincia">@provincia.Descripcion</option>
                    }
                </select>
            </div>


            <div class="form-group">
                <label for="distrito">Distrito:</label>
                <select class="form-control" id="distrito" name="IdDistrito">
                    <option value="">Seleccione un distrito</option>
                </select>
            </div>
            </br>
            </br>
            
            <div class="form-group">
                <input type="submit" value="Grabar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>

@if (ViewBag.Mensaje != null)
{
    <div class="alert alert-info">
        @ViewBag.Mensaje
    </div>
}



<script>
    $(document).ready(function () {
        $('#provincia').change(function () {
            var idProvincia = $(this).val();
            if (idProvincia) {
                $.ajax({
                    url: '@Url.Action("GetDistritosByProvincia", "Colaborador")',
                    type: 'GET',
                    data: { idProvincia: idProvincia },
                    dataType: 'json',
                    success: function (data) {
                        $('#distrito').empty();
                        $('#distrito').append($('<option>').val('').text('Seleccione un distrito'));
                        $.each(data, function (i, item) {
                            $('#distrito').append($('<option>').val(item.idDistrito).text(item.descripcion));
                        });
                    }
                });
            } else {
                $('#distrito').empty();
                $('#distrito').append($('<option>').val('').text('Seleccione un distrito'));
            }
        });
    });

</script>